### ISSUE TITLE
Requesting a podspec update :)

### ISSUE THREAD

**Issue by DimaVartanian** [jnjosh/JNJProgressButton#1]
all of your updates would be nice, but my main concern is the error I get during a pod install:

"[!] Unable to read the license file for the spec `JNJProgressButton (0.1)`"

It looks like you tagged to 0.1 before you actually created the license file, so cocoapods isn't seeing it.

**Comment by jnjosh** [comment]
I'm surprised that passed the cocoapods lint script. Sorry about that. I just committed a new podspec and a pull request to cocoapods:

https://github.com/CocoaPods/Specs/pull/3142

**Comment by DimaVartanian** [comment]
awesome!
